[workspace]
members = [
	"domain",
	"usecase",
	"application",
	"infrastructure",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.89"
async-trait = "0.1.82"
chrono = "0.4.38"
serde = "1.0.210"
tokio = "1.40.0"

